#pragma config(Sensor, dgtl1,  Floor1,         sensorTouch)
#pragma config(Sensor, dgtl2,  Floor2,         sensorTouch)
#pragma config(Sensor, dgtl3,  Floor3,         sensorTouch)
#pragma config(Sensor, dgtl4,  Floor4,         sensorTouch)
#pragma config(Sensor, dgtl5,  Sonar,          sensorSONAR_cm)
#pragma config(Sensor, dgtl8,  Floor4,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  Floor3,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, Floor2,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, Floor1,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, Top,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           Flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           Lift,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:
  Team Members:
  Date:
  Section:


  Task Description:


  Pseudocode:

*/

task main()
{                                     //Program begins, insert code within curly braces

	while(1==1)
		{
			while(SensorValue(Floor1) == 1)
				{
					if (SensorValue(Sonar) > 3.5)
						{
							startMotor(Lift, 40);
						}
					else
						{
							stopMotor(Lift);
						}
				}
///////////////////////////////////////////////////////

			while(SensorValue(Floor2) == 1)
				{
					if (SensorValue(Sonar) > 7)
						{
							startMotor(Lift, 40);
						}
					if (SensorValue(Sonar) < 7)
						{
							startMotor(Lift, -40);
						}
					else
						{
							stopMotor(Lift);
						}
				}

///////////////////////////////////////////////////////
			while(SensorValue(Floor3) == 1)
				{
					if (SensorValue(Sonar) > 10)
						{
							startMotor(Lift, 40);
						}
					if (SensorValue(Sonar) < 10)
						{
							startMotor(Lift, -40);
						}
					else
						{
							stopMotor(Lift);
						}
				}
///////////////////////////////////////////////////////

			while(SensorValue(Floor4) == 1)
				{
					if (SensorValue(Sonar) > 13)
						{
							startMotor(Lift, 40);
						}
					if (SensorValue(Sonar) < 13)
						{
							startMotor(Lift, -40);
						}
					else
						{
							stopMotor(Lift);
						}
				}

		}
///////////////////////////////////////////////////////
		while(1==1)
		{
			turnFlashlightOn(Flashlight);
			if (SensorValue(Sonar) == 3.5)
			{
				turnLEDOn(Floor1);
			}
			if (SensorValue(Sonar) == 7)
			{
				turnLEDOn(Floor2);
			}
			if (SensorValue(Sonar) == 10)
			{
				turnLEDOn(Floor3);
			}
			if (SensorValue(Sonar) == 13)
			{
				turnLEDOn(Floor4);
			}
			else
			{
				turnLEDOff(Floor1);
				turnLEDOff(Floor2);
				turnLEDOff(Floor3);
				turnLEDOff(Floor4);
			}
		}
}
